### ISSUE TITLE
Issues upon running on a new system

### ISSUE THREAD

**Issue by jogardi** [AlmogBaku/openai-streaming#5]
Here's some fixes in case someone else gets these issues. The problem is I'm using new packages 
If you see  `has no attribute 'model_json_schema'` then change line 75 of decorator.py to `parameters = model.schema()`

Also, you might need to change line 225 of stream_processing to `if not hasattr(choice, "delta"):`

**Comment by AlmogBaku** [comment]
thanks!, ill try to fix it asap

**Comment by AlmogBaku** [comment]
done
